# Home-manager module for ksh26
# Provides programs.ksh with kshrc generation, tool integrations,
# FPATH autoloading, per-TTY history, and build-time syntax checking.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.programs.ksh;

  aliasesStr = builtins.concatStringsSep "\n" (
    lib.mapAttrsToList (k: v: "alias ${k}=${lib.escapeShellArg v}") (
      config.home.shellAliases // cfg.shellAliases
    )
  );

  trackedAliasesStr = builtins.concatStringsSep "\n" (
    lib.mapAttrsToList (k: v: "alias -t ${k}=${lib.escapeShellArg v}") cfg.trackedAliases
  );

  shellOptsStr = builtins.concatStringsSep "\n" (
    builtins.map (o: "set -o ${o}") cfg.shellOptions
  );

  sessionVarsStr = config.lib.shell.exportAll cfg.sessionVariables;

  functionsStr =
    lib.optionalString (cfg.functionsDir != null) ''
      FPATH="${cfg.functionsDir}:''${FPATH:-}"
      for _hm_func in "${cfg.functionsDir}"/*; do
        [[ -f "$_hm_func" ]] || continue
        _hm_name=''${_hm_func##*/}
        case "$_hm_name" in
          *.sh|*.ksh|README*) continue ;;
          *) typeset -fu "$_hm_name" 2>/dev/null ;;
        esac
      done
      unset _hm_func _hm_name
    '';

  # direnv works via a PS1 discipline function that runs `direnv export bash`
  # on every prompt — the output is plain export/unset, nothing bash-specific.
  #
  # zoxide uses posix mode with a dedup wrapper so `zoxide add` only fires on
  # actual directory changes (bash does this natively; posix mode doesn't).
  integrationsStr = lib.optionalString config.programs.direnv.enable ''
    _hm_direnv=${lib.getExe pkgs.direnv}
    PS1.get() {
      eval "$("$_hm_direnv" export bash 2>/dev/null)"
    }
  '' + lib.optionalString config.programs.zoxide.enable ''
    eval "$(${lib.getExe config.programs.zoxide.package} init posix --hook prompt)"
    # Wrap the hook with directory-change dedup (posix mode calls zoxide add
    # on every prompt; this limits it to actual cd events like bash/zsh do)
    __zoxide_oldpwd="$(__zoxide_pwd)"
    __zoxide_hook() {
      typeset _pwd
      _pwd="$(__zoxide_pwd)"
      if [[ "$__zoxide_oldpwd" != "$_pwd" ]]; then
        __zoxide_oldpwd="$_pwd"
        command zoxide add -- "$_pwd"
      fi
    }
  '';

  kshrcContent = ''
    # Generated by home-manager — do not edit

    # System-wide ksh config (nix environment, PATH, aliases)
    [[ -f /etc/kshrc ]] && . /etc/kshrc

    # Non-interactive guard
    [[ -o interactive ]] || return 0

    # Source hm session variables
    for _hm_f in /etc/profiles/per-user/$USER/etc/profile.d/*.sh; do
      [[ -f "$_hm_f" ]] && . "$_hm_f"
    done
    unset _hm_f

    # History — per-TTY for session isolation
    typeset _hm_histdir="${cfg.historyDir}"
    typeset _hm_tty
    _hm_tty=$(tty 2>/dev/null) || _hm_tty="$$"
    HISTFILE="$_hm_histdir/''${_hm_tty//\//_}"
    HISTSIZE=${toString cfg.historySize}
    # Migrate from single history file to per-TTY directory
    [[ -f "$_hm_histdir" ]] && mv "$_hm_histdir" "$_hm_histdir.old"
    [[ -d "$_hm_histdir" ]] || mkdir -p "$_hm_histdir"
    unset _hm_tty _hm_histdir

    ${lib.optionalString (cfg.sessionVariables != { }) ''
      # Session variables
      ${sessionVarsStr}
    ''}
    ${lib.optionalString (cfg.functionsDir != null) ''
      # FPATH autoloading
      ${functionsStr}
    ''}
    ${lib.optionalString (aliasesStr != "") ''
      # Aliases
      ${aliasesStr}
    ''}
    ${lib.optionalString (trackedAliasesStr != "") ''
      # Tracked aliases
      ${trackedAliasesStr}
    ''}
    ${lib.optionalString (cfg.profileExtra != "") ''
      # Profile extra
      ${cfg.profileExtra}
    ''}
    ${lib.optionalString (cfg.initExtra != "") ''
      # User init
      ${cfg.initExtra}
    ''}
    ${lib.optionalString (integrationsStr != "") ''
      # Tool integrations
      ${integrationsStr}
    ''}
    ${lib.optionalString (cfg.shellOptions != [ ]) ''
      # Shell options (after plugins so set -o vi doesn't reset traps)
      ${shellOptsStr}
    ''}
  '';

  kshrcFile = pkgs.writeTextFile {
    name = "kshrc";
    text = kshrcContent;
    checkPhase = ''
      ${lib.getExe' cfg.package "ksh"} -n "$target"
    '';
  };
in
{
  options.programs.ksh = {
    enable = lib.mkEnableOption "ksh shell configuration";

    package = lib.mkPackageOption pkgs "ksh26" { };

    shellOptions = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      example = [
        "vi"
        "globstar"
        "trackall"
      ];
      description = "Shell options to set via `set -o`.";
    };

    historySize = lib.mkOption {
      type = lib.types.int;
      default = 50000;
      description = "Number of history entries to keep.";
    };

    historyDir = lib.mkOption {
      type = lib.types.str;
      default = "\${XDG_DATA_HOME:-$HOME/.local/share}/ksh/history";
      description = "Directory for per-TTY history files.";
    };

    shellAliases = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      example = {
        em = "emacsclient -cn";
      };
      description = ''
        Regular aliases. Merged with `home.shellAliases`;
        per-program values override global ones.
      '';
    };

    trackedAliases = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      example = {
        ls = "eza";
      };
      description = ''
        Tracked aliases (`alias -t`). These follow PATH changes
        so the resolved path stays current.
      '';
    };

    sessionVariables = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      description = "Environment variables exported at shell startup.";
    };

    functionsDir = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = ''
        Directory of ksh autoload functions. When set, the directory
        is prepended to FPATH and all files in it (except *.sh, *.ksh,
        README*) are marked for autoloading via `typeset -fu`.
      '';
    };

    profileExtra = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Extra commands for login shell initialisation.";
    };

    initExtra = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = ''
        Extra commands for interactive shell initialisation.
        Appended last in the generated kshrc.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [ cfg.package ];

    home.file.".kshrc".source = kshrcFile;
  };
}
