#!/bin/sh

# iffe.sh — regression tests for the iffe feature-detection tool
#
# Ported from iffe.tst (AT&T regress format) to standalone POSIX shell.
# All 18 test groups from the original are preserved.
#
# Requirements: CC on PATH (runs inside nix develop)
# Usage: sh tests/infra/iffe.sh

set -o nounset

# ── Configuration ────────────────────────────────────────────────────

PACKAGEROOT=${PACKAGEROOT:-$(cd "$(dirname "$0")/../.." && pwd)}
IFFE=$PACKAGEROOT/src/cmd/INIT/iffe.sh
CC=${CC:-cc}

pass=0
fail=0
errors=""

# ── Temp directory ───────────────────────────────────────────────────

tmpdir=$(mktemp -d "${TMPDIR:-/tmp}/iffe-test.XXXXXX") || exit 1
trap 'rm -rf "$tmpdir"' EXIT
cd "$tmpdir" || exit 1

# ── Helpers ──────────────────────────────────────────────────────────

# Normalize iffe version strings so tests don't break on version bumps
normalize() {
	sed -e 's/iffe version [0-9][0-9-]*/iffe version VERSION/' \
	    -e 's/[	 ]*$//'
}

# Run iffe and capture output. Sets _stdout, _stderr, _exit.
run_iffe() {
	sh "$IFFE" "$@" >"$tmpdir/_stdout" 2>"$tmpdir/_stderr"
	_exit=$?
	_stdout=$(cat "$tmpdir/_stdout")
	_stderr=$(cat "$tmpdir/_stderr")
}

# Compare actual vs expected, version-normalized. Returns 0 on match.
check_match() {
	local label=$1
	local actual=$2
	local expected=$3
	local a_norm e_norm

	a_norm=$(printf '%s\n' "$actual" | normalize)
	e_norm=$(printf '%s\n' "$expected" | normalize)

	if [ "$a_norm" = "$e_norm" ]; then
		return 0
	else
		printf '  MISMATCH (%s):\n' "$label"
		printf '  expected:\n%s\n' "$e_norm" | sed 's/^/    /'
		printf '  actual:\n%s\n' "$a_norm" | sed 's/^/    /'
		return 1
	fi
}

# Assert iffe output matches expectations
# Usage: assert_iffe "description" "expected_exit" "expected_stdout" "expected_stderr"
#   Pass "" for stdout/stderr to skip that check
assert_iffe() {
	local desc=$1
	local exp_exit=${2:-0}
	local exp_stdout=${3:-}
	local exp_stderr=${4:-}
	local ok=true

	if [ "$_exit" != "$exp_exit" ]; then
		printf '  exit: expected %s, got %s\n' "$exp_exit" "$_exit"
		ok=false
	fi
	if [ -n "$exp_stdout" ]; then
		check_match "stdout" "$_stdout" "$exp_stdout" || ok=false
	fi
	if [ -n "$exp_stderr" ]; then
		check_match "stderr" "$_stderr" "$exp_stderr" || ok=false
	fi

	if $ok; then
		pass=$((pass + 1))
	else
		fail=$((fail + 1))
		errors="${errors}  FAIL: ${desc}\n"
		printf 'FAIL: %s\n' "$desc"
	fi
}

# ── Test groups ──────────────────────────────────────────────────────

test_01_command_line_basics() {
	printf '%s\n' "TEST 01: command line basics"

	run_iffe -r -v - hdr stdio
	assert_iffe "01: hdr stdio (cmdline)" 0 \
'/* : : generated by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _hdr_stdio	1	/* #include <stdio.h> ok */
#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is stdio.h a header ... yes'

	run_iffe -r -v -s posix - hdr stdio
	assert_iffe "01: hdr stdio (posix)" 0 \
'/* : : generated by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _hdr_stdio	1	/* #include <stdio.h> ok */
#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is stdio.h a header ... yes'

	run_iffe -r -v - hdr stdio,limits
	assert_iffe "01: hdr stdio,limits" 0 \
'/* : : generated by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _hdr_stdio	1	/* #include <stdio.h> ok */
#define _hdr_limits	1	/* #include <limits.h> ok */
#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is stdio.h a header ... yes
iffe: test: is limits.h a header ... yes'

	run_iffe -r -v - hdr,lib no_foo_bar,no_bar_foo stdio.h
	assert_iffe "01: hdr,lib nonexistent" 0 \
'/* : : generated by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _hdr_stdio	1	/* #include <stdio.h> ok */
#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is stdio.h a header ... yes
iffe: test: is no_foo_bar.h a header ... no
iffe: test: is no_bar_foo.h a header ... no
iffe: test: is no_foo_bar a library function ... no
iffe: test: is no_bar_foo a library function ... no'

	# Separated form (hdr : lib) should produce same output
	run_iffe -r -v - hdr no_foo_bar,no_bar_foo stdio.h : lib no_foo_bar,no_bar_foo stdio.h
	assert_iffe "01: hdr : lib separated" 0 \
'/* : : generated by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _hdr_stdio	1	/* #include <stdio.h> ok */
#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is stdio.h a header ... yes
iffe: test: is no_foo_bar.h a header ... no
iffe: test: is no_bar_foo.h a header ... no
iffe: test: is no_foo_bar a library function ... no
iffe: test: is no_bar_foo a library function ... no'
}

test_02_file_input_basics() {
	printf '%s\n' "TEST 02: file input basics"

	printf '%s\n' 'hdr stdio' > t1.iffe
	run_iffe -r -v - t1.iffe
	assert_iffe "02: file input hdr stdio" 0 \
'/* : : generated from t1.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _hdr_stdio	1	/* #include <stdio.h> ok */
#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is stdio.h a header ... yes'

	printf '%s\n' 'hdr stdio,limits' > t2.iffe
	run_iffe -r -v - t2.iffe
	assert_iffe "02: file input hdr stdio,limits" 0 \
'/* : : generated from t2.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _hdr_stdio	1	/* #include <stdio.h> ok */
#define _hdr_limits	1	/* #include <limits.h> ok */
#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is stdio.h a header ... yes
iffe: test: is limits.h a header ... yes'

	printf '%s\n' 'hdr,lib no_foo_bar,no_bar_foo stdio.h' > t3.iffe
	run_iffe -r -v - t3.iffe
	assert_iffe "02: file input hdr,lib combined" 0 \
'/* : : generated from t3.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _hdr_stdio	1	/* #include <stdio.h> ok */
#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is stdio.h a header ... yes
iffe: test: is no_foo_bar.h a header ... no
iffe: test: is no_bar_foo.h a header ... no
iffe: test: is no_foo_bar a library function ... no
iffe: test: is no_bar_foo a library function ... no'

	# Separated form in file
	printf '%s\n' 'hdr no_foo_bar,no_bar_foo stdio.h
lib no_foo_bar,no_bar_foo stdio.h' > t3.iffe
	run_iffe -r -v - t3.iffe
	assert_iffe "02: file input hdr/lib separated" 0 \
'/* : : generated from t3.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _hdr_stdio	1	/* #include <stdio.h> ok */
#endif' ""
}

test_03_nested_if() {
	printf '%s\n' "TEST 03: nested if"

	# if hdr stdio → true, if lib open → true → HIT 1
	cat > t.iffe <<'EOF'
iff ifelse
if hdr stdio
	if lib open {
		HIT 1
	}
	elif lib close {
		HIT 2
	}
	else {
		HIT 3
	}
	endif
elif hdr limits {
	HIT 4
}
else {
	HIT 5
}
endif
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "03: nested if (stdio+open)" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _ifelse_H
#define _ifelse_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _hdr_stdio	1	/* #include <stdio.h> ok */
#define _lib_open	1	/* open() in default lib(s) */
	HIT 1

#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is stdio.h a header ... yes
iffe: test: is open a library function ... yes'

	# if hdr _XXX_stdio → false, elif hdr limits → true → HIT 4
	cat > t.iffe <<'EOF'
iff ifelse
if hdr _XXX_stdio
	if lib open {
		HIT 1
	}
	elif lib close {
		HIT 2
	}
	else {
		HIT 3
	}
	endif
elif hdr limits {
	HIT 4
}
else {
	HIT 5
}
endif
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "03: nested if (_XXX_stdio → limits)" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _ifelse_H
#define _ifelse_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _hdr_limits	1	/* #include <limits.h> ok */
HIT 4

#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is _XXX_stdio.h a header ... no
iffe: test: is limits.h a header ... yes'

	# All false → HIT 5
	cat > t.iffe <<'EOF'
iff ifelse
if hdr _XXX_stdio
	if lib open {
		HIT 1
	}
	elif lib close {
		HIT 2
	}
	else {
		HIT 3
	}
	endif
elif hdr _XXX_limits {
	HIT 4
}
else {
	HIT 5
}
endif
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "03: nested if (all false → HIT 5)" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _ifelse_H
#define _ifelse_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
HIT 5

#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is _XXX_stdio.h a header ... no
iffe: test: is _XXX_limits.h a header ... no'

	# stdio true, _XXX_open false, close true → HIT 2
	cat > t.iffe <<'EOF'
iff ifelse
if hdr stdio
	if lib _XXX_open {
		HIT 1
	}
	elif lib close {
		HIT 2
	}
	else {
		HIT 3
	}
	endif
elif hdr limits {
	HIT 4
}
else {
	HIT 5
}
endif
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "03: nested if (stdio+close → HIT 2)" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _ifelse_H
#define _ifelse_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _hdr_stdio	1	/* #include <stdio.h> ok */
#define _lib_close	1	/* close() in default lib(s) */
	HIT 2

#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is stdio.h a header ... yes
iffe: test: is _XXX_open a library function ... no
iffe: test: is close a library function ... yes'

	# stdio true, both libs false → HIT 3
	cat > t.iffe <<'EOF'
iff ifelse
if hdr stdio
	if lib _XXX_open {
		HIT 1
	}
	elif lib _XXX_close {
		HIT 2
	}
	else {
		HIT 3
	}
	endif
elif hdr limits {
	HIT 4
}
else {
	HIT 5
}
endif
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "03: nested if (both libs false → HIT 3)" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _ifelse_H
#define _ifelse_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _hdr_stdio	1	/* #include <stdio.h> ok */
	HIT 3

#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is stdio.h a header ... yes
iffe: test: is _XXX_open a library function ... no
iffe: test: is _XXX_close a library function ... no'

	# mem stat.st_atime → true, ATIME + YESTIME
	cat > t.iffe <<'EOF'
iff ifelse
if mem stat.st_atime sys/types.h sys/stat.h {
	#define ATIME	1
}
elif mem stat.st_ctime sys/types.h sys/stat.h {
	#define CTIME	1
}
elif mem stat.st_mtime sys/types.h sys/stat.h {
	#define MTIME	1
}
else pass{ no_stat_time=1 }end {
	#define NOTIME	1
}
endif
if ( !no_stat_time ) {
	#define YESTIME	1
}
endif
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "03: mem stat.st_atime (ATIME+YESTIME)" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _ifelse_H
#define _ifelse_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _sys_stat	1	/* #include <sys/stat.h> ok */
#define _mem_st_atime_stat	1	/* st_atime is a member of struct stat */
#define ATIME	1

#define YESTIME	1

#endif' ""

	# set explicit + iff previous
	cat > t.iffe <<'EOF'
set	explicit
iff	previous
hdr	stdio
if hdr stdio {
	OK
}
else {
	OK
}
endif
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "03: set explicit + iff previous" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _previous_H
#define _previous_H	1
#define _hdr_stdio	1	/* #include <stdio.h> ok */
OK

#endif' ""
}

test_04_variable_macro_override() {
	printf '%s\n' "TEST 04: test variable/macro override"

	cat > t.iffe <<'EOF'
iff macro
HAVE_STDIO = hdr stdio
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "04: HAVE_STDIO = hdr stdio" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _macro_H
#define _macro_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define HAVE_STDIO	1	/* #include <stdio.h> ok */
#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is stdio.h a header ... yes'

	cat > t.iffe <<'EOF'
iff macro
if hdr - stdio {
	#define HIT 1
}
endif
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "04: hdr - stdio (suppress define)" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _macro_H
#define _macro_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define HIT 1

#endif' ""

	# if - hdr stdio (same as above, different syntax)
	cat > t.iffe <<'EOF'
iff macro
if - hdr stdio {
	#define HIT 1
}
endif
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "04: if - hdr stdio" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _macro_H
#define _macro_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define HIT 1

#endif' ""

	# if ? hdr stdio
	cat > t.iffe <<'EOF'
iff macro
if ? hdr stdio {
	#define HIT 1
}
endif
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "04: if ? hdr stdio" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _macro_H
#define _macro_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define HIT 1

#endif' ""

	# HAVE_STDIO in if/endif + exp
	cat > t.iffe <<'EOF'
iff macro
if HAVE_STDIO = hdr stdio {
	#define HIT 1
}
endif
if ( HAVE_STDIO ) {
	#define TOO ALSO
}
endif
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "04: HAVE_STDIO + exp" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _macro_H
#define _macro_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define HAVE_STDIO	1	/* #include <stdio.h> ok */
#define HIT 1

#define TOO ALSO

#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is stdio.h a header ... yes
iffe: test: is ( HAVE_STDIO ) true ... yes'

	# exp ALSO HAVE_STDIO
	cat > t.iffe <<'EOF'
iff macro
if HAVE_STDIO = hdr stdio {
	#define HIT 1
}
endif
exp ALSO HAVE_STDIO
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "04: exp ALSO HAVE_STDIO" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _macro_H
#define _macro_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define HAVE_STDIO	1	/* #include <stdio.h> ok */
#define HIT 1

#define ALSO	1	/* HAVE_STDIO is true */
#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is stdio.h a header ... yes
iffe: test: is HAVE_STDIO true ... yes'

	# ALSO = ( HAVE_STDIO )
	cat > t.iffe <<'EOF'
iff macro
if HAVE_STDIO = hdr stdio {
	#define HIT 1
}
endif
ALSO = ( HAVE_STDIO )
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "04: ALSO = ( HAVE_STDIO )" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _macro_H
#define _macro_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define HAVE_STDIO	1	/* #include <stdio.h> ok */
#define HIT 1

#define ALSO	1	/* ( HAVE_STDIO ) is true */
#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is stdio.h a header ... yes
iffe: test: is ( HAVE_STDIO ) true ... yes'
}

test_05_code_option_sequence() {
	printf '%s\n' "TEST 05: test code option sequence"

	# tst seq with -DA=1 first alternative matches
	cat > t.iffe <<'EOF'
iff macro
tst seq - -DA=1 - -DB=1 note{ long int type }end compile{
	#if A == 1 && B == 0
	#define t		long
	#else
	#define t		error
	#endif
	t n = 0;
}end
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "05: tst seq -DA=1 first (A==1,B==0)" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _macro_H
#define _macro_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _seq	1	/* long int type */
#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: long int type ... yes'

	# A==0, B==1 → second alternative
	cat > t.iffe <<'EOF'
iff macro
tst seq - -DA=1 - -DB=1 note{ long int type }end compile{
	#if A == 0 && B == 1
	#define t		long
	#else
	#define t		error
	#endif
	t n = 0;
}end
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "05: tst seq second (A==0,B==1)" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _macro_H
#define _macro_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _seq	1	/* long int type */
#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: long int type ...
iffe: test: long int type ... yes'

	# Neither matches → no define
	cat > t.iffe <<'EOF'
iff macro
tst seq - -DA=1 - -DB=1 note{ long int type }end compile{
	#if A == 0 && B == 0
	#define t		long
	#else
	#define t		error
	#endif
	t n = 0;
}end
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "05: tst seq neither matches" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _macro_H
#define _macro_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: long int type ...
iffe: test: long int type ... no'

	# if tst (first) → body
	cat > t.iffe <<'EOF'
iff macro
if tst - -DA=1 - -DB=1 note{ long int type }end compile{
	#if A == 1 && B == 0
	#define t		long
	#else
	#define t		error
	#endif
	t n = 0;
}end {
	#define seq 1
}
endif
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "05: if tst first matches" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _macro_H
#define _macro_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
/* long int type */
#define seq 1

#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: long int type ... yes'

	# 3-way: -DN=1
	cat > t.iffe <<'EOF'
iff macro
if tst - -DN=1 - -DN=2 - -DN=3 note{ long int type }end compile{
	#if N == 1
	#define t		long
	#else
	#define t		error
	#endif
	t n = 0;
}end {
	#define seq 1
}
endif
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "05: 3-way N==1" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _macro_H
#define _macro_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
/* long int type */
#define seq 1

#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: long int type ... yes'

	# 3-way: N==2
	cat > t.iffe <<'EOF'
iff macro
if tst - -DN=1 - -DN=2 - -DN=3 note{ long int type }end compile{
	#if N == 2
	#define t		long
	#else
	#define t		error
	#endif
	t n = 0;
}end {
	#define seq 1
}
endif
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "05: 3-way N==2" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _macro_H
#define _macro_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
/* long int type */
#define seq 1

#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: long int type ...
iffe: test: long int type ... yes'

	# 3-way: N==3
	cat > t.iffe <<'EOF'
iff macro
if tst - -DN=1 - -DN=2 - -DN=3 note{ long int type }end compile{
	#if N == 3
	#define t		long
	#else
	#define t		error
	#endif
	t n = 0;
}end {
	#define seq 1
}
endif
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "05: 3-way N==3" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _macro_H
#define _macro_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
/* long int type */
#define seq 1

#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: long int type ...
iffe: test: long int type ...
iffe: test: long int type ... yes'

	# 3-way: none match
	cat > t.iffe <<'EOF'
iff macro
if tst - -DN=1 - -DN=2 - -DN=3 note{ long int type }end compile{
	#if N == 0
	#define t		long
	#else
	#define t		error
	#endif
	t n = 0;
}end {
	#define seq 1
}
endif
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "05: 3-way none match" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _macro_H
#define _macro_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: long int type ...
iffe: test: long int type ...
iffe: test: long int type ... no'
}

test_06_block_side_effects() {
	printf '%s\n' "TEST 06: block side effects"

	# output{} with exit 0 → HIT
	cat > t.iffe <<'EOF'
iff -
tst	output{
	int
	main(void)
	{
		printf("HIT\n");
		return 0;
	}
}end
EOF
	run_iffe -r - t.iffe
	assert_iffe "06: output{} exit 0" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#define _sys_types	1	/* #include <sys/types.h> ok */
HIT' ""

	# Anonymous tst - output{} exit 0 → suppressed define, HIT in output
	cat > t.iffe <<'EOF'
iff
tst	- output{
	int
	main(void)
	{
		printf("HIT\n");
		return 0;
	}
}end
EOF
	run_iffe -r - t.iffe
	assert_iffe "06: anonymous tst - output{}" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#define _sys_types	1	/* #include <sys/types.h> ok */
HIT' ""

	# output{} with exit 1 → no HIT (test fails)
	cat > t.iffe <<'EOF'
iff
tst	- output{
	int
	main(void)
	{
		printf("HIT\n");
		return 1;
	}
}end
EOF
	run_iffe -r - t.iffe
	assert_iffe "06: output{} exit 1 → no HIT" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#define _sys_types	1	/* #include <sys/types.h> ok */' ""

	# nooutput{} with exit 1 → inverted: HIT appears
	cat > t.iffe <<'EOF'
iff
tst	- nooutput{
	int
	main(void)
	{
		printf("HIT\n");
		return 1;
	}
}end
EOF
	run_iffe -r - t.iffe
	assert_iffe "06: nooutput{} exit 1 → HIT" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#define _sys_types	1	/* #include <sys/types.h> ok */
HIT' ""
}

test_07_diagnostics() {
	printf '%s\n' "TEST 07: diagnostics"

	# Unknown feature test
	printf '%s\n' 'tst foo' > t.iffe
	run_iffe -r - t.iffe
	assert_iffe "07: unknown feature test" 1 "" \
'iffe: t.iffe:1: tst: unknown feature test'

	# Missing endif
	printf '%s\n' 'if (1)' > t.iffe
	run_iffe -r - t.iffe
	assert_iffe "07: missing endif (if (1))" 1 "" \
'iffe: t.iffe:1: missing endif'

	# Missing endif (bare if)
	printf '%s\n' 'if' > t.iffe
	run_iffe -r - t.iffe
	assert_iffe "07: missing endif (bare if)" 1 "" \
'iffe: t.iffe:1: missing endif'

	# endif without if
	printf '%s\n' 'endif' > t.iffe
	run_iffe -r - t.iffe
	assert_iffe "07: endif without if" 1 "" \
'iffe: t.iffe:1: endif: no matching if'

	# Missing closing brace
	printf '%s' 'if {
}end' > t.iffe
	run_iffe -r - t.iffe
	assert_iffe "07: missing }" 1 "" \
'iffe: t.iffe:1: missing }'
}

test_08_negation_consternation() {
	printf '%s\n' "TEST 08: negation consternation"

	printf '%s\n' 'npt fopen,fooon stdio.h' > t.iffe

	# Default: only positive results
	run_iffe -r - t.iffe
	assert_iffe "08: npt default" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _hdr_stdlib	1	/* #include <stdlib.h> ok */
#define _hdr_unistd	1	/* #include <unistd.h> ok */
#define _hdr_stdio	1	/* #include <stdio.h> ok */
#define _npt_fooon	1	/* fooon() needs a prototype */
#endif' ""

	# -u: undef negatives
	run_iffe -r -u - t.iffe
	assert_iffe "08: npt -u (undef)" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _hdr_stdlib	1	/* #include <stdlib.h> ok */
#define _hdr_unistd	1	/* #include <unistd.h> ok */
#define _hdr_stdio	1	/* #include <stdio.h> ok */
#undef	_npt_fopen		/* fopen() does not need a prototype */
#define _npt_fooon	1	/* fooon() needs a prototype */
#endif' ""

	# -a: define 0 for negatives
	run_iffe -r -a - t.iffe
	assert_iffe "08: npt -a (define 0)" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _hdr_stdlib	1	/* #include <stdlib.h> ok */
#define _hdr_unistd	1	/* #include <unistd.h> ok */
#define _hdr_stdio	1	/* #include <stdio.h> ok */
#define _npt_fopen	0	/* fopen() does not need a prototype */
#define _npt_fooon	1	/* fooon() needs a prototype */
#endif' ""

	# -C: HAVE_ naming convention
	run_iffe -r -C - t.iffe
	assert_iffe "08: npt -C (HAVE_)" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define HAVE_SYS_TYPES_H	1	/* #include <sys/types.h> ok */
#define HAVE_STDLIB_H	1	/* #include <stdlib.h> ok */
#define HAVE_UNISTD_H	1	/* #include <unistd.h> ok */
#define HAVE_STDIO_H	1	/* #include <stdio.h> ok */
#define HAVE_FOPEN_DECL	1	/* fopen() does not need a prototype */
#undef	HAVE_FOOON_DECL		/* fooon() needs a prototype */
#endif' ""

	# Custom variable names with ! negation
	cat > t.iffe <<'EOF'
NEED_FOPEN = npt fopen stdio.h
HAVE_FOPEN = ! npt fopen stdio.h
NEED_FOOON = npt fooon stdio.h
HAVE_FOOON = ! npt fooon stdio.h
EOF
	run_iffe -r - t.iffe
	assert_iffe "08: npt custom names with !" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _hdr_stdlib	1	/* #include <stdlib.h> ok */
#define _hdr_unistd	1	/* #include <unistd.h> ok */
#define _hdr_stdio	1	/* #include <stdio.h> ok */
#define HAVE_FOPEN	1	/* fopen() does not need a prototype */
#define NEED_FOOON	1	/* fooon() needs a prototype */
#endif' ""
}

test_09_exp_vs_if() {
	printf '%s\n' "TEST 09: exp vs. if"

	# !_tst_false → true, ONE
	cat > t.iffe <<'EOF'
_tst_false = ( 0 )
_tst_true = ( 1 )
exp	_tst_hit !_tst_false {
	ONE
}
exp	_tst_hit !_tst_hit&_tst_true pass{
cat <<!
	TWO $_tst_false $_tst_true
!
}end
exp	_tst_hit !_tst_hit&_tst_true {
	THREE
}
EOF
	run_iffe -r - t.iffe
	assert_iffe "09: !_tst_false → ONE" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _tst_true	1	/* ( 1 ) is true */
#define _tst_hit	1	/* !_tst_false is true */
/* !_tst_false */
ONE

#endif' ""

	# !_tst_true → false, then !hit&true → TWO
	cat > t.iffe <<'EOF'
_tst_false = ( 0 )
_tst_true = ( 1 )
exp	_tst_hit !_tst_true {
	ONE
}
exp	_tst_hit !_tst_hit&_tst_true pass{
cat <<!
	TWO $_tst_false $_tst_true
!
}end
exp	_tst_hit !_tst_hit&_tst_true {
	THREE
}
EOF
	run_iffe -r - t.iffe
	assert_iffe "09: !_tst_true → TWO pass{}" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _tst_true	1	/* ( 1 ) is true */
#define _tst_hit	1	/* !_tst_hit&_tst_true is true */
TWO 0 1
#endif' ""

	# !_tst_true, then !hit&false → THREE
	cat > t.iffe <<'EOF'
_tst_false = ( 0 )
_tst_true = ( 1 )
exp	_tst_hit !_tst_true {
	ONE
}
exp	_tst_hit !_tst_hit&_tst_false pass{
cat <<!
	TWO $_tst_false $_tst_true
!
}end
exp	_tst_hit !_tst_hit&_tst_true {
	THREE
}
EOF
	run_iffe -r - t.iffe
	assert_iffe "09: !_tst_true, false pass → THREE" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _tst_true	1	/* ( 1 ) is true */
#define _tst_hit	1	/* !_tst_hit&_tst_true is true */
/* !_tst_hit&_tst_true */
THREE

#endif' ""

	# All false → nothing
	cat > t.iffe <<'EOF'
_tst_false = ( 0 )
_tst_true = ( 1 )
exp	_tst_hit !_tst_true {
	ONE
}
exp	_tst_hit !_tst_hit&_tst_false pass{
cat <<!
	TWO $_tst_false $_tst_true
!
}end
exp	_tst_hit !_tst_hit&_tst_false {
	THREE
}
EOF
	run_iffe -r - t.iffe
	assert_iffe "09: all false → empty" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _tst_true	1	/* ( 1 ) is true */
#endif' ""

	# if/elif/else with ( ! ) expressions
	cat > t.iffe <<'EOF'
_tst_false = ( 0 )
_tst_true = ( 1 )
if ( ! _tst_false ) {
	ONE
}
elif ( _tst_true ) pass{
cat <<!
	TWO
!
}end
else {
	THREE
}
endif
EOF
	run_iffe -r - t.iffe
	assert_iffe "09: if ( ! _tst_false ) → ONE" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _tst_true	1	/* ( 1 ) is true */
ONE

#endif' ""

	# if ( ! _tst_true ) → elif → TWO
	cat > t.iffe <<'EOF'
_tst_false = ( 0 )
_tst_true = ( 1 )
if ( ! _tst_true ) {
	ONE
}
elif ( _tst_true ) pass{
cat <<!
	TWO
!
}end
else {
	THREE
}
endif
EOF
	run_iffe -r - t.iffe
	assert_iffe "09: if ( ! _tst_true ) → TWO pass" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _tst_true	1	/* ( 1 ) is true */
TWO
#endif' ""

	# Both if and elif false → THREE
	cat > t.iffe <<'EOF'
_tst_false = ( 0 )
_tst_true = ( 1 )
if ( ! _tst_true ) {
	ONE
}
elif ( _tst_false ) pass{
cat <<!
	TWO
!
}end
else {
	THREE
}
endif
EOF
	run_iffe -r - t.iffe
	assert_iffe "09: both false → THREE" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _tst_true	1	/* ( 1 ) is true */
THREE

#endif' ""

	# yes{} block with false condition → nothing
	cat > t.iffe <<'EOF'
_tst_false = ( 0 )
_tst_true = ( 1 )
if ( ! _tst_true ) yes{
	typedef struct
	{
		int		dd_fd;		/* file descriptor		*/
	} DIR;
}end
endif
EOF
	run_iffe -r - t.iffe
	assert_iffe "09: yes{} with false → nothing" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _tst_true	1	/* ( 1 ) is true */
#endif' ""

	# false, else OK
	cat > t.iffe <<'EOF'
_tst_false = ( 0 )
_tst_true = ( 1 )
if ( ! _tst_true ) {
	typedef struct
	{
		int		dd_fd;		/* file descriptor		*/
	} DIR;
}
else {
	OK
}
endif
EOF
	run_iffe -r - t.iffe
	assert_iffe "09: false → else OK" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _tst_true	1	/* ( 1 ) is true */
OK

#endif' ""
}

test_10_exp_details() {
	printf '%s\n' "TEST 10: exp details"

	cat > t.iffe <<'EOF'
_str = "string"
_hdr = <header>
_aaa = ( 0 )
_zzz = ( 1 )
( _str )
( ! _str )
( _hdr )
( ! _hdr )
( _aaa )
( ! _aaa )
( _zzz )
( ! _zzz )
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "10: exp details" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _str	"string"
#define _hdr	<header>
#define _zzz	1	/* ( 1 ) is true */
#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is ( 0 ) true ... no
iffe: test: is ( 1 ) true ... yes
iffe: test: is ( _str ) true ... yes
iffe: test: is ( ! _str ) true ... no
iffe: test: is ( _hdr ) true ... yes
iffe: test: is ( ! _hdr ) true ... no
iffe: test: is ( _aaa ) true ... no
iffe: test: is ( ! _aaa ) true ... yes
iffe: test: is ( _zzz ) true ... yes
iffe: test: is ( ! _zzz ) true ... no'
}

test_11_set_nodefine() {
	printf '%s\n' "TEST 11: set [no]define"

	cat > t.iffe <<'EOF'
set nodefine
mem stat.st_mtime sys/types.h sys/stat.h
set define
mem stat.st_mode sys/types.h sys/stat.h
if ( _mem_st_mtime_stat ) {
	1
}
endif
if ( _mem_st_mode_stat ) {
	2
}
endif
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "11: set nodefine/define" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _mem_st_mode_stat	1	/* st_mode is a member of struct stat */
1

2

#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is sys/stat.h a header ... yes
iffe: test: is stat a type or typedef ... no
iffe: test: is st_mtime a member of struct stat ... yes
iffe: test: is st_mode a member of struct stat ... yes
iffe: test: is ( _mem_st_mtime_stat ) true ... yes
iffe: test: is ( _mem_st_mode_stat ) true ... yes'
}

test_12_non_opaque_mem() {
	printf '%s\n' "TEST 12: non-opaque mem"

	printf '%s\n' 'typedef struct opaque OPAQUE;' > t.h
	run_iffe -r -v - mem OPAQUE -I. t.h
	assert_iffe "12: opaque struct" 0 \
'/* : : generated by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _hdr_t	1	/* #include <t.h> ok */
#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is t.h a header ... yes
iffe: test: is OPAQUE a type or typedef ... no
iffe: test: is struct OPAQUE a non-opaque struct ... no'

	printf '%s\n' 'struct nonopaque { int pad; };
typedef struct nonopaque NONOPAQUE;' > t.h
	run_iffe -r -v - mem NONOPAQUE -I. t.h
	assert_iffe "12: non-opaque struct" 0 \
'/* : : generated by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _hdr_t	1	/* #include <t.h> ok */
#define _mem_NONOPAQUE	1	/* NONOPAQUE is a non-opaque struct */
#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is t.h a header ... yes
iffe: test: is NONOPAQUE a type or typedef ... yes
iffe: test: is NONOPAQUE a non-opaque struct ... yes'
}

test_13_key_states() {
	printf '%s\n' "TEST 13: key states"

	cat > t.iffe <<'EOF'
key	int
key	const =
key	foo
key	bar =
key	aha = huh = int
key	chr = char = int
EOF

	run_iffe -r -v - t.iffe
	assert_iffe "13: key states (default)" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _key_int	1	/* int is a reserved keyword */
#define _key_const	1	/* const is a reserved keyword */
#define bar	 	/* default for reserved keyword bar */
#define aha	int	/* default for reserved keyword aha */
#define _key_char	1	/* char is a reserved keyword */
#define chr	char	/* alternate for reserved keyword chr */
#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is int a reserved keyword ... yes
iffe: test: is const a reserved keyword ... yes
iffe: test: is foo a reserved keyword ... no
iffe: test: is bar a reserved keyword ... no
iffe: test: is aha a reserved keyword ... no
iffe: test: is huh a reserved keyword ... no
iffe: test: is chr a reserved keyword ... no
iffe: test: is char a reserved keyword ... yes'

	run_iffe -u -r -v - t.iffe
	assert_iffe "13: key states (-u undef)" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _key_int	1	/* int is a reserved keyword */
#define _key_const	1	/* const is a reserved keyword */
#undef	_key_foo		/* foo is not a reserved keyword */
#undef	_key_bar		/* bar is not a reserved keyword */
#define bar	 	/* default for reserved keyword bar */
#undef	_key_huh		/* huh is not a reserved keyword */
#define aha	int	/* default for reserved keyword aha */
#define _key_char	1	/* char is a reserved keyword */
#define chr	char	/* alternate for reserved keyword chr */
#endif' ""

	run_iffe -a -r -v - t.iffe
	assert_iffe "13: key states (-a define 0)" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define _key_int	1	/* int is a reserved keyword */
#define _key_const	1	/* const is a reserved keyword */
#define _key_foo	0	/* foo is not a reserved keyword */
#define _key_bar	0	/* bar is not a reserved keyword */
#define bar	 	/* default for reserved keyword bar */
#define _key_huh	0	/* huh is not a reserved keyword */
#define aha	int	/* default for reserved keyword aha */
#define _key_char	1	/* char is a reserved keyword */
#define chr	char	/* alternate for reserved keyword chr */
#endif' ""

	run_iffe -C -r -v - t.iffe
	assert_iffe "13: key states (-C HAVE_)" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define HAVE_SYS_TYPES_H	1	/* #include <sys/types.h> ok */
#define HAVE_INT_RESERVED	1	/* int is a reserved keyword */
#define HAVE_CONST_RESERVED	1	/* const is a reserved keyword */
#undef	HAVE_FOO_RESERVED		/* foo is not a reserved keyword */
#undef	HAVE_BAR_RESERVED		/* bar is not a reserved keyword */
#define bar	 	/* default for reserved keyword bar */
#undef	HAVE_HUH_RESERVED		/* huh is not a reserved keyword */
#define aha	int	/* default for reserved keyword aha */
#define HAVE_CHAR_RESERVED	1	/* char is a reserved keyword */
#define chr	char	/* alternate for reserved keyword chr */
#endif' ""
}

test_14_inc_file() {
	printf '%s\n' "TEST 14: inc file"

	printf '%s\n' '#define bar_foo ALL
#define _foo_bar SOME' > t_lib.h

	# inc without '.' — only _prefixed names visible
	cat > t.iffe <<'EOF'
inc t_lib.h
if ( bar_foo ) {
	#define all 1
}
elif ( _foo_bar ) {
	#define some 1
}
endif
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "14: inc (no dot, _foo_bar visible)" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define some 1

#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is ( bar_foo ) true ... no
iffe: test: is ( _foo_bar ) true ... yes'

	# inc with '.' — all defines visible
	cat > t.iffe <<'EOF'
inc t_lib.h .
if ( bar_foo ) {
	#define all 1
}
elif ( _foo_bar ) {
	#define ok 1
}
endif
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "14: inc with dot (all visible)" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define all 1

#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is ( bar_foo ) true ... yes'

	# inc with '. ?' — warns about ?
	cat > t.iffe <<'EOF'
inc t_lib.h . ?
if ( bar_foo ) {
	#define all 1
}
elif ( _foo_bar ) {
	#define ok 1
}
endif
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "14: inc with dot ? (warning)" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define all 1

#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: t.iffe:1: warning: ?: operands ignored
iffe: test: is ( bar_foo ) true ... yes'

	# inc nonexistent file → error
	printf '%s\n' 'inc foo_lib.h' > t.iffe
	run_iffe -r -v - t.iffe
	assert_iffe "14: inc nonexistent file" 1 "" \
'iffe: test: is sys/types.h a header ... yes
iffe: t.iffe:1: foo_lib.h: file not found'

	# inc with no path
	printf '%s\n' 'inc' > t.iffe
	run_iffe -r -v - t.iffe
	assert_iffe "14: inc no path" 1 "" \
'iffe: test: is sys/types.h a header ... yes
iffe: t.iffe:1: path expected'
}

test_15_knr_compatibility() {
	printf '%s\n' "TEST 15: KnR compatibility"

	cat > t.iffe <<'EOF'

if ( 1 ) {
		#define all 1
}
endif
if ( 2 ) {
                #define some 1
}
endif
cat{
#define a 1
 #define b 2
  #define c 3
	 #define d 4
}end
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "15: KnR indentation + cat{}" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#define all 1

#define some 1

#define a 1
#define b 2
#define c 3
#define d 4

#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is ( 1 ) true ... yes
iffe: test: is ( 2 ) true ... yes
iffe: test: cat{ ... }end ... yes'
}

test_16_define_extern_include_print() {
	printf '%s\n' "TEST 16: { define extern include print }"

	cat > t.iffe <<'EOF'

print	/* test header */
header	stdio.h
define	EOF	-1
define	FoobaR	(a,b)	((a)+(b))
define	FoomaC	-1
extern	fopen	FILE*	(char*, char*)
extern	BarfoO	struct barfoo*	(int)
extern	Tab_lE	struct barfoo*	[10]
EOF
	run_iffe -r -v - t.iffe
	assert_iffe "16: define/extern/include/print" 0 \
'/* test header */
/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#include <stdio.h>
#define FoobaR(a,b)	((a)+(b))
#define FoomaC	-1
extern struct barfoo*	BarfoO(int);
extern struct barfoo*	Tab_lE[10];
#endif' \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is stdio.h a header ... yes
iffe: test: is EOF a macro ... yes
iffe: test: is FoobaR a macro ... no
iffe: test: is FoomaC a macro ... no
iffe: test: is fopen a symbol that needs a prototype ... no
iffe: test: is BarfoO a symbol that needs a prototype ... yes
iffe: test: is Tab_lE a symbol that needs a prototype ... yes'
}

test_17_features_to_FEATURE() {
	printf '%s\n' "TEST 17: features/* => FEATURE/*"

	mkdir -p features FEATURE
	printf '%s\n' 'header stdio.h' > features/stdio
	run_iffe -r -v run features/stdio
	assert_iffe "17: features/stdio → FEATURE/stdio" 0 "" \
'iffe: test: is sys/types.h a header ... yes
iffe: test: is stdio.h a header ... yes'

	# Check the FEATURE output file
	if [ -f FEATURE/stdio ]; then
		local feat_content
		feat_content=$(cat FEATURE/stdio | normalize)
		local expected='/* : : generated from features/stdio by iffe version VERSION : : */
#ifndef _REGRESS
#define _REGRESS	1
#define _sys_types	1	/* #include <sys/types.h> ok */
#include <stdio.h>
#endif'
		if [ "$feat_content" = "$expected" ]; then
			pass=$((pass + 1))
		else
			fail=$((fail + 1))
			errors="${errors}  FAIL: 17: FEATURE/stdio content mismatch\n"
			printf 'FAIL: 17: FEATURE/stdio content mismatch\n'
		fi
	else
		fail=$((fail + 1))
		errors="${errors}  FAIL: 17: FEATURE/stdio not created\n"
		printf 'FAIL: 17: FEATURE/stdio not created\n'
	fi
	rm -rf features FEATURE
}

test_18_api_ver() {
	printf '%s\n' "TEST 18: api + ver"

	cat > t.iffe <<'EOF'
iff api
ver foo 20100606
ver bar 19840919

api foo 19991231 dis dat tother
api foo 20100601 dat
api foo 20100606 dis
api bar 19991231 moe larry shemp
api bar 20020202 curly
api bar 20030303 shemp
api bar 20040404 joe_b
api bar 20050505 joe_d

EOF
	run_iffe -r -v - t.iffe
	assert_iffe "18: api + ver" 0 \
'/* : : generated from t.iffe by iffe version VERSION : : */
#ifndef _api_H
#define _api_H	1
#define _sys_types	1	/* #include <sys/types.h> ok */

#define FOO_VERSION	20100606
#define BAR_VERSION	19840919
#define FOOAPI(rel)	( _BLD_foo || !_API_foo || _API_foo >= rel )

#if !defined(_API_foo) && defined(_API_DEFAULT)
#define _API_foo	_API_DEFAULT
#endif

#if FOOAPI(20100601)
#undef	dat
#define dat	dat_20100601
#elif _API_foo >= 19991231
#undef	dat
#define dat	dat_19991231
#endif

#if FOOAPI(20100606)
#undef	dis
#define dis	dis_20100606
#elif _API_foo >= 19991231
#undef	dis
#define dis	dis_19991231
#endif

#if FOOAPI(19991231)
#undef	tother
#define tother	tother_19991231
#endif

#define _API_foo_MAP	"dat_20100601 dat_19991231 dis_20100606 dis_19991231 tother_19991231"
#define BARAPI(rel)	( _BLD_bar || !_API_bar || _API_bar >= rel )

#if !defined(_API_bar) && defined(_API_DEFAULT)
#define _API_bar	_API_DEFAULT
#endif

#if BARAPI(20020202)
#undef	curly
#define curly	curly_20020202
#endif

#if BARAPI(20040404)
#undef	joe_b
#define joe_b	joe_b_20040404
#endif

#if BARAPI(20050505)
#undef	joe_d
#define joe_d	joe_d_20050505
#endif

#if BARAPI(19991231)
#undef	larry
#define larry	larry_19991231
#endif

#if BARAPI(19991231)
#undef	moe
#define moe	moe_19991231
#endif

#if BARAPI(20030303)
#undef	shemp
#define shemp	shemp_20030303
#elif _API_bar >= 19991231
#undef	shemp
#define shemp	shemp_19991231
#endif

#define _API_bar_MAP	"curly_20020202 joe_b_20040404 joe_d_20050505 larry_19991231 moe_19991231 shemp_20030303 shemp_19991231"

#endif' \
'iffe: test: is sys/types.h a header ... yes'
}

# ── Run all tests ────────────────────────────────────────────────────

test_01_command_line_basics
test_02_file_input_basics
test_03_nested_if
test_04_variable_macro_override
test_05_code_option_sequence
test_06_block_side_effects
test_07_diagnostics
test_08_negation_consternation
test_09_exp_vs_if
test_10_exp_details
test_11_set_nodefine
test_12_non_opaque_mem
test_13_key_states
test_14_inc_file
test_15_knr_compatibility
test_16_define_extern_include_print
test_17_features_to_FEATURE
test_18_api_ver

# ── Summary ──────────────────────────────────────────────────────────

total=$((pass + fail))
printf '\n---\n%d/%d iffe tests pass\n' "$pass" "$total"
if [ "$fail" -gt 0 ]; then
	printf '\nFailed tests:\n%b' "$errors"
	exit 1
fi
exit 0
